# Generated by Django 5.2.4 on 2025-07-16 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
